### ISSUE TITLE
Flask requirement breaks package use

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/idutils#105]
Package version (if known): 1.3

## Describe the bug
Addition of https://github.com/inveniosoftware/idutils/blob/aded7b990cee5f967c7ff4e43bbac98795541dce/idutils/proxies.py#L16 breaks idutils usage outside of flask. I use idutils in a bunch of python scripts that aren't flask applications, so the flask requirement breaks the import.

## Steps to Reproduce
1. Write a python script with `from idutils import normalize_doi`
2. Type `python script.py`
3. See 'ModuleNotFoundError: No module named 'flask''

## Expected behavior
idutils should be able to be used in a non-flask context

**Comment by zzacharo** [comment]
Hey @tmorrell ! Sorry for that, tomorrow we will fix this :)
