### ISSUE TITLE
arXiv: allow verbose post 2007 strings

### ISSUE THREAD

**Issue by mihaibivol** [inveniosoftware/idutils#14]
In inspirehep we have some arXiv numbers tokenized as:
```
arXiv:yymm.xxxx [hep-th]
```

The current implementation does not allow for any trailing strings after the number even if in the arXiv documentation it's said that:

> Note that the identifier no longer contains any classification information and thus reclassification after an article is announced is possible. Classification information is indicated in other ways. For example, the stamp added to the side of the PDF versions of arXiv articles has the form:
>
> arXiv:0706.0001v1 [q-bio.CB] 1 Jun 2007

`arXiv:0706.0001v1 [q-bio.CB] 1 Jun 2007` is not exactly an arXiv number, but, it might be useful for idutils to accept such strings as arXiv numbers.

**Comment by jirikuncar** [comment]
@mihaibivol can you provide any details?

**Comment by mihaibivol** [comment]
@jirikuncar in inspire references some of the report numbers we have on references are specified as `arXiv:yymm.xxxx [hep-th]`. Currently idutils says this is not an arXiv number. It might be good for idutils to say that this is an arXiv number.

**Comment by mihaibivol** [comment]
@jirikuncar If on the `idutils` side you are OK with accepting trailing strings after post-2007 arXiv numbers I am happy to send a PR :)

**Comment by jirikuncar** [comment]
@mihaibivol as long as it's "strict" (e.g. `(\[[^]]\]( [0-9]\{1,2\} ...to be defined...)?)?`) it should not harm anybody.

**Comment by lnielsen** [comment]
As I understand https://arxiv.org/help/arxiv_identifier, the classification (i.e. ``[q-bio.CB]``) is not part of the post-2007 identifiers, and thus should not be considered a valid arXiv identifier.

What you have is instead an **arXiv reference** (according to http://arxiv.org/help/faq/references), and thus I think it would be more appropriate to add a new methods ``is_arxiv_reference`` + ``normalize_arxiv_reference``.

Do you use the method standalone or via ``detect_identifier_schemes``? I'm not sure if it's appropriate to include it in ``detect_identifier_schemes`` as it's a reference including an identifier but not an actual identifier.

**Comment by mihaibivol** [comment]
@lnielsen it's a fair point for the library. That's why I didn't use `detect_identifier_schemes` but rather wrote some ugly workarounds for getting things decently normalized when porting from legacy.

As I later spoke with @kaplun, it seems that this is actually a INSPIRE use-case in which we harvested lots of __arXiv references__ when we actually wanted only the __identifiers__. I'd rather leave the workaround in our repo until we have things migrated rather than cluttering `idutils` with a specific logic.

Our code would "write" better if the `arxiv identifier` regex would also accept `arxiv identifiers` so even if I added some __reference__ specific code here I would still need the use-case in which I transform references into identifiers.

**Comment by mihaibivol** [comment]
This is the code where we use this https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/references/processors.py#L152 and it's rather a small place in which we gather most of the corner cases that we have when migrating / building new references within HEP Records.

**Comment by lnielsen** [comment]
> I'd rather leave the workaround in our repo until we have things migrated rather than cluttering idutils with a specific logic.

👍 

Should I close the issue or leave it open?

**Comment by mihaibivol** [comment]
@lnielsen I think it's better to close it and apply some wontfix tag (which I can't do myself)
