### ISSUE TITLE
Change isbnid requirment to isbnid_fork

### ISSUE THREAD

**Issue by rikirenz** [inveniosoftware/idutils#26]
The library https://github.com/nekobcn/isbnid that we use to normalize an ISBN identifier in the package is not supported anymore.
As you can see here: https://github.com/nekobcn/isbnid/issues, we have opened several issues in the last months, but the author of the package is not replaying.
For this reason we have decide to fork the project and start to maintain it. The new package `isbnid_fork` (https://github.com/inspirehep/isbnid) is already available with pip.

The only thing that should change in `inveniosoftware/idutils` project is this requirement:  https://github.com/inveniosoftware/idutils/blob/33577263914923d117c5e86a1491daf08cbf35b2/setup.py#L26; from `isbnid>=0.3.4'` to `isbnid_fork>=0.4.4`.

**Comment by jirikuncar** [comment]
What about moving the `isbnid_fork` to `inveniosoftware(-contrib)`?

**Comment by rikirenz** [comment]
@david-caro @kaplun What do you think?

**Comment by david-caro** [comment]
That would be ok, though I'd first make it work where it is now. Maybe open an issue for later.

**Comment by kaplun** [comment]
Makes sense :+1: we'll transfer it soon.

**Comment by lnielsen** [comment]
Closed by c2a757a2ab0cbed7c5a21edffe0685371b78f6ad
