### ISSUE TITLE
test always passes due to operator precedence

### ISSUE THREAD

**Issue by szymonlopaciuk** [inveniosoftware/idutils#32]
In the tests, on lines https://github.com/inveniosoftware/idutils/blob/master/tests/test_idutils.py#L145-L146:
```python
assert idutils.normalize_pid(i, expected_schemes[0]) == normalized_value or i
```
Instead, wasn't the intended functionality:
```python
assert idutils.normalize_pid(i, expected_schemes[0]) == (normalized_value or i)
```
Otherwise, `i` (which is a test ID, never empty) will always make the assertion true, regardless of the value of the equality?

**Comment by lnielsen** [comment]
Correct :-) Thanks for spotting it. Will you make a PR?

**Comment by szymonlopaciuk** [comment]
I will look into it, I saw there was a test case that will need checking
