### ISSUE TITLE
add support for ascl

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/idutils#36]
ASCL ids look like arXiv ids. For that reason the creators recommend always including the `ascl:` prefix in the values, i.e. `ascl:1908.011` vs. `1908.011`, so that should be taken in to account for the regex. The generated `idutils.to_url` of course would have to use the non-prefixed part to generate the URL, i.e. `http://ascl.net/1908.011`.

Some information about the identifiers: http://ascl.net/home/getwp/351

**Comment by slint** [comment]
Closed via #50
