### ISSUE TITLE
Support for ISBN and ISSN normalisation

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/idutils#4]
I note the existance of https://github.com/arthurdejong/python-stdnum which supports, among many formats, ISBNs and ISSNs, checking and normalization.

Would be great to wrap this library within idutils.

**Comment by lnielsen** [comment]
After discussion IRL with @kaplun:

- We support validation of ISBNs and ISSNs.
- We do not support normalisation of ISBNs/ISSNs.
- Normalisation of ISBNs are quite complex, so using external lib would be preferable.

*Proposed solution:*

- [ ] Add soft dependencies on python-stdnum or isbnlib. If the dependency is not installed, we implement a simple normalisation function which strips the entire ISBN.
- [ ] Implement ISSN validation
