### ISSUE TITLE
isbn: isbnlib alters global socket timeout

### ISSUE THREAD

**Issue by mihaibivol** [inveniosoftware/idutils#8]
We had some errors in running `inspirehep` in debug mode because of some race conditions and we narrowed it down to `isbnlib` which is calling `socket.setdefaulttimeout` upon import (https://github.com/xlcnd/isbnlib/blob/master/isbnlib/config.py#L22).

While we could work around the issue, maybe it would be better to use another library that does the same thing.

@lnielsen What do you think?

**Comment by lnielsen** [comment]
No problem in changing the library. It's the only real external dependency and was introduced in 1a85e4f56c734440cbc031f14a4ab8eacda63b07. Just be sure to choose a library which as little external dependencies as possible, in order to keep this library small and agile.
