### ISSUE TITLE
Support expanded ORCID range

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/idutils#87]
Package version (if known): v1.2

## Describe the bug
ORCID has expanded the range of possible identifiers, so we need treat identifiers in the range 0009-0000-0000-0000 and 0009-0010-0000-0000 as valid. https://support.orcid.org/hc/en-us/articles/360006973973-What-is-the-relationship-between-ISNI-and-ORCID-

**Comment by slint** [comment]
FYI, this is fixed in #88 and will be released in `v1.2.1`.
